### ISSUE TITLE
Restore password

### ISSUE THREAD

**Issue by JoseKill09** [UselessStudio/TeleOTP#2]
Hello,

I've been using the bot from my main Telegram account, and I didn't pay much attention to the password I set, so I don't remember it now.

I think it is necessary to create some password recovery system, or an option so that if the account cannot be recovered, at least create a new one (And add each TOTP token again).

Thanks in advance and regards.

**Comment by lunnaholy** [comment]
Glad to see you :)

The ability to recover the master password is not included in the original concept of secure TOTP storage - it is difficult to implement any of the recovery mechanisms in a way that is still sufficiently secure.

The ability to reset your account if you forget your master password will be added in future updates.

**Comment by LowderPlay** [comment]
Implemented in f166b61911e6f7343c84fad67964b3262eb69052
