### ISSUE TITLE
Are you willing to support more languages?

### ISSUE THREAD

**Issue by roziscoding** [UselessStudio/TeleOTP#51]
I'd love to help translating this to brazilian portuguese.
Would that be interesting? If so, how should I go about adding a new language?

**Comment by LowderPlay** [comment]
Hi! 
I've added a new language to Crowdin. 
Feel free to translate at https://crowdin.com/project/teleotp/pt-BR. I'll add the translations on the next release.
Thanks for the help!

**Comment by roziscoding** [comment]
Done :D
